# Generated by Django 5.2.5 on 2025-09-08 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultQueryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=1)),
                ('option_text', models.TextField(blank=True)),
                ('image_text', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorldBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageRender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('ready', 'ready'), ('failed', 'failed')], default='pending', max_length=16)),
                ('image_rel', models.CharField(blank=True, max_length=512)),
                ('last_turn_image_rel', models.CharField(blank=True, max_length=512)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renders', to='shared.option')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True)),
                ('question_generated_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_generated_at', models.DateTimeField(blank=True, null=True)),
                ('query_text', models.TextField(blank=True)),
                ('context_block', models.TextField(blank=True)),
                ('user_choice', models.CharField(blank=True, max_length=1)),
                ('displayed_image_rel', models.CharField(blank=True, max_length=512)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='shared.session')),
            ],
            options={
                'ordering': ['year'],
            },
        ),
        migrations.AddField(
            model_name='option',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shared.turn'),
        ),
        migrations.AddField(
            model_name='session',
            name='world_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shared.worldbackground'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('turn', 'label')},
        ),
    ]
