# Generated by Django 5.2.5 on 2025-09-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turn',
            old_name='context_block',
            new_name='question_query_text',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='query_text',
        ),
        migrations.AddField(
            model_name='option',
            name='scenario',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='option',
            name='scenario_query_text',
            field=models.TextField(blank=True),
        ),
    ]
