# Generated by Django 5.1.4 on 2025-09-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='story_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
