# Generated by Django 5.2.5 on 2025-09-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultquerylist',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='defaultquerylist',
            name='weight',
        ),
    ]
