# Generated by Django 5.2.5 on 2025-09-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_update_for_2option_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turn',
            name='description',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='description_generated_at',
        ),
        migrations.RemoveField(
            model_name='turn',
            name='question_query_text',
        ),
        migrations.AddField(
            model_name='option',
            name='question_query_text',
            field=models.TextField(blank=True),
        ),
    ]
