# Generated by Django 5.1.4 on 2025-09-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_turn_story_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='scenario_summary',
            field=models.TextField(blank=True),
        ),
    ]
