# Image generation logic
from dataclasses import dataclass
import json
import time
import uuid
import requests
from typing import Dict, Any
import re

COMFYUI_BASE_URL = "http://127.0.0.1:8000"
CLIENT_ID = str(uuid.uuid4())
POLL_INTERVAL_LIMIT = 1.0
POLL_TIMEOUT_LIMIT = 120

prompt_world_map = {}

@dataclass
class ImageLocation:
    filename: str
    subfolder: str
    type: str = 'output'

# exported workflow
EXPORTED_WORKFLOW = {
  "3": {
    "inputs": {
      "seed": 49289279412421,
      "steps": 20,
      "cfg": 8,
      "sampler_name": "euler",
      "scheduler": "normal",
      "denoise": 1,
      "model": [
        "4",
        0
      ],
      "positive": [
        "6",
        0
      ],
      "negative": [
        "7",
        0
      ],
      "latent_image": [
        "5",
        0
      ]
    },
    "class_type": "KSampler",
    "_meta": {
      "title": "KSampler"
    }
  },
  "4": {
    "inputs": {
      "ckpt_name": "dreamshaper_7.safetensors"
    },
    "class_type": "CheckpointLoaderSimple",
    "_meta": {
      "title": "Load Checkpoint"
    }
  },
  "5": {
    "inputs": {
      "width": 512,
      "height": 512,
      "batch_size": 1
    },
    "class_type": "EmptyLatentImage",
    "_meta": {
      "title": "Empty Latent Image"
    }
  },
  "6": {
    "inputs": {
      "text": "a world with tears where everybody can trade their memories",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Prompt)"
    }
  },
  "7": {
    "inputs": {
      "text": "text, watermark",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Prompt)"
    }
  },
  "8": {
    "inputs": {
      "samples": [
        "3",
        0
      ],
      "vae": [
        "4",
        2
      ]
    },
    "class_type": "VAEDecode",
    "_meta": {
      "title": "VAE Decode"
    }
  },
  "9": {
    "inputs": {
      "filename_prefix": "ComfyUI",
      "images": [
        "8",
        0
      ]
    },
    "class_type": "SaveImage",
    "_meta": {
      "title": "Save Image"
    }
  }
}

# emojis TBD (if the llm could give emojis)
def clean_llm_description(llm_description: str) -> str:
    """    
    Input:
        llm_description (str): The raw world description text generated by the LLM.    
    Output:
        clean_prompt (str): A cleaned, single-line prompt string suitable for node 6.
    """
    # for llm response:
    #   llm_description should be no longer than 70 words as stable 1.5 encoder only encode first 77 tokens

    if not llm_description or not llm_description.strip():
        raise ValueError("LLM description is empty.")

    trimmed_description = llm_description.strip()

    # collapse newlines, tabs, and multiple spaces into a single space
    normalized_description = re.sub(r'\s+', ' ', trimmed_description)

    clean_prompt = normalized_description

    return clean_prompt

def build_prompt_payload(clean_prompt: str) -> Dict[str, Any]:
    """
    Input:
        clean_prompt (str): The cleaned, single-line world description from clean_llm_description().

    Output:
        payload (dict): {"prompt": <workflow>}
    """
    workflow_copy = json.loads(json.dumps(EXPORTED_WORKFLOW))

    # chuck cleaned description to node 6
    node6 = workflow_copy.get("6")
    node6_inputs = node6.get("inputs", {})
    node6_inputs["text"] = clean_prompt

    # send request to ComfyUI
    prompt_payload = {"prompt": workflow_copy}
    return prompt_payload

def enqueue_render(prompt_payload: Dict[str, Any]) -> str:
    """
    Input:
        prompt_payload (dict): from build_prompt_payload()
    Output:
        prompt_id (str): returned by ComfyUI after sending a request
    """
    body = {'prompt': prompt_payload['prompt'], 'client_id': CLIENT_ID}
    response = requests.post(f'{COMFYUI_BASE_URL}/prompt', json = body)
    data = response.json()
    prompt_id = data.get('prompt_id')
    if not prompt_id:
        raise RuntimeError(f'/prompt response missing prompt_id.')
    return prompt_id

def map_world_to_prompt(world_id: str, prompt_id: str) -> None:
    
    prompt_world_map[world_id] = prompt_id

def get_prompt_id_for_world(world_id: str) -> str:
    try:
        return prompt_world_map[world_id]
    except:
        raise KeyError(f'Unknown worldId: {world_id}')

def get_image_location(prompt_id: str, 
                       timeout_seconds: int = POLL_TIMEOUT_LIMIT, 
                       interval_seconds: float = POLL_INTERVAL_LIMIT) -> ImageLocation:
    """
    Poll ComfyUI /history/{prompt_id} until an image appears in outputs.

    Returns:
        ImageLocation
    Raises:
        TimeoutError if no image appears before timeout.
        RuntimeError for non-200 responses.
    """
    history_url = f'{COMFYUI_BASE_URL}/history/{prompt_id}'
    deadline_epoch = time.time() + timeout_seconds

    while time.time() < deadline_epoch:
        response = requests.get(history_url)
        if response.status_code != 200:
            raise RuntimeError(f'failed to GET history/')

        history_payload = response.json() or {}

        entry = history_payload.get(prompt_id) or history_payload
        outputs_by_node = entry.get('outputs') or {}

        for node_id, node_output in outputs_by_node.items():
            images = node_output.get('images') or []
            if images:
                first_image = images[0]
                return ImageLocation(
                    filename=first_image.get('filename', ''),
                    subfolder=first_image.get('subfolder', ''),
                    type=first_image.get('type', 'output')
                )

        time.sleep(interval_seconds)

    raise TimeoutError('Timed out while waiting for image.')

def fetch_png_bytes(image_location: ImageLocation) -> bytes:
    """
    Input:
        image_location (ImageLocation)
    Output:
        png_bytes (bytes)
    """
    params = {
        'filename': image_location.filename,
        'subfolder': image_location.subfolder,
        'type': image_location.type
    }
    response = requests.get(f'{COMFYUI_BASE_URL}/view', params=params, stream=True)
    response.raise_for_status()
    return response.content



# ---------------------- test -----------------------

des = "           A speculative future city where memories are traded like currency: glowing neural marketplaces, " \
"people exchanging    luminous memory orbs, brain-linked kiosks pulsing with circuits, surreal architecture shaped by thought. " \
"Streets shimmer with fragments   of others' pasts drifting like holograms. Faces half-formed with borrowed recollections blur into fluid identities. " \
"The scene is speculative, artistic, dreamlike—vivid yet unsettling, merging science and imagination in symbolic, painterly style."

cleaned_text = clean_llm_description(des)

payload = build_prompt_payload(cleaned_text)

# print(json.dumps(payload, indent=2, ensure_ascii=False))

prompt_id = enqueue_render(payload)
# print(prompt_id)

imagelocation = get_image_location(prompt_id)
print(imagelocation.filename, imagelocation.subfolder, imagelocation.type)

content = fetch_png_bytes(imagelocation)
print(content[:8])