# Image generation logic
from dataclasses import dataclass
import json
import time
import uuid
import requests
from typing import Dict, Any
import re

COMFYUI_BASE_URL = "http://127.0.0.1:8000"
CLIENT_ID = str(uuid.uuid4())

POLL_INTERVAL_LIMIT = 1.0
POLL_TIMEOUT_LIMIT = 120

# prompt_world_map = {}

@dataclass
class ImageLocation:
    filename: str
    subfolder: str
    type: str = 'output'

# exported workflow
# might later change node settings after performance testing
EXPORTED_WORKFLOW = {
  "3": {
    "inputs": {
      "seed": 49289279412421,
      "steps": 20,
      "cfg": 8,
      "sampler_name": "euler",
      "scheduler": "normal",
      "denoise": 1,
      "model": [
        "4",
        0
      ],
      "positive": [
        "6",
        0
      ],
      "negative": [
        "7",
        0
      ],
      "latent_image": [
        "5",
        0
      ]
    },
    "class_type": "KSampler",
    "_meta": {
      "title": "KSampler"
    }
  },
  "4": {
    "inputs": {
      "ckpt_name": "dreamshaper_7.safetensors"
    },
    "class_type": "CheckpointLoaderSimple",
    "_meta": {
      "title": "Load Checkpoint"
    }
  },
  "5": {
    "inputs": {
      "width": 512,
      "height": 512,
      "batch_size": 1
    },
    "class_type": "EmptyLatentImage",
    "_meta": {
      "title": "Empty Latent Image"
    }
  },
  "6": {
    "inputs": {
      "text": "a world with tears where everybody can trade their memories",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Prompt)"
    }
  },
  "7": {
    "inputs": {
      "text": "text, watermark",
      "clip": [
        "4",
        1
      ]
    },
    "class_type": "CLIPTextEncode",
    "_meta": {
      "title": "CLIP Text Encode (Prompt)"
    }
  },
  "8": {
    "inputs": {
      "samples": [
        "3",
        0
      ],
      "vae": [
        "4",
        2
      ]
    },
    "class_type": "VAEDecode",
    "_meta": {
      "title": "VAE Decode"
    }
  },
  "9": {
    "inputs": {
      "filename_prefix": "ComfyUI",
      "images": [
        "8",
        0
      ]
    },
    "class_type": "SaveImage",
    "_meta": {
      "title": "Save Image"
    }
  }
}

# llm_description should be no longer than 70 words as stable 1.5 encoder only encode first 77 tokens
def truncate_words(text: str, max_words: int = 70) -> str:
    parts = text.split()
    if len(parts) <= max_words:
        return text
    return ' '.join(parts[:max_words])

def clean_llm_description(llm_description: str) -> str:
    """    
    Input:
        llm_description (str): The raw world description text generated by the LLM.    
    Output:
        clean_prompt (str): A cleaned prompt string for node 6.
    """
    if not llm_description or not llm_description.strip():
        raise ValueError("LLM description is empty.")
    
    # remove white spaces
    normalized = re.sub(r'\s+', ' ', llm_description.strip())

    return truncate_words(normalized, max_words=70)

def build_prompt_payload(clean_prompt: str) -> Dict[str, Any]:
    """
    Input:
        clean_prompt (str): The cleaned world description from clean_llm_description().
    Output:
        payload (dict): {"prompt": <workflow>}
    """
    workflow_copy = json.loads(json.dumps(EXPORTED_WORKFLOW))

    # chuck cleaned description to node 6
    node6 = workflow_copy.get("6")
    node6_inputs = node6.get("inputs", {})
    node6_inputs["text"] = clean_prompt

    prompt_payload = {"prompt": workflow_copy}
    return prompt_payload

def enqueue_render(prompt_payload: Dict[str, Any]) -> str:
    """
    Input:
        prompt_payload (dict): from build_prompt_payload()
    Output:
        prompt_id (str): returned by ComfyUI after sending a request
    """
    body = {'prompt': prompt_payload['prompt'], 'client_id': CLIENT_ID}
    response = requests.post(f'{COMFYUI_BASE_URL}/prompt', json = body)
    data = response.json()
    prompt_id = data.get('prompt_id')
    if not prompt_id:
        raise RuntimeError(f'/prompt response missing prompt_id.')
    return prompt_id

def get_image_location(prompt_id: str, 
                       timeout_seconds: int = POLL_TIMEOUT_LIMIT, 
                       interval_seconds: float = POLL_INTERVAL_LIMIT) -> ImageLocation:
    
    history_url = f'{COMFYUI_BASE_URL}/history/{prompt_id}'
    deadline = time.time() + timeout_seconds

    # continuously checking if image is generated
    while time.time() < deadline:
        response = requests.get(history_url)
        if response.status_code != 200:
            raise RuntimeError(f'failed to GET history/')

        history_payload = response.json() or {}

        entry = history_payload.get(prompt_id) or {}
        outputs_by_node = entry.get('outputs') or {}

        for node_id, node_output in outputs_by_node.items():
            images = node_output.get('images') or []
            if images: # if image exists, return its data for later fetching from /view?...
                first_image = images[0]
                return ImageLocation(
                    filename=first_image.get('filename', ''),
                    subfolder=first_image.get('subfolder', ''),
                    type=first_image.get('type', 'output')
                )

        time.sleep(interval_seconds)

    raise TimeoutError('Timed out while waiting for image.')

def fetch_png_bytes(image_location: ImageLocation) -> bytes:
    """
    Input:
        image_location (ImageLocation): from get_image_location()
    Output:
        png_bytes (bytes): 
    """
    params = {
        'filename': image_location.filename,
        'subfolder': image_location.subfolder,
        'type': image_location.type
    }
    response = requests.get(f'{COMFYUI_BASE_URL}/view', params=params, stream=True)
    response.raise_for_status()
    return response.content

# def map_world_to_prompt(world_id: str, prompt_id: str) -> None:
    
#     prompt_world_map[world_id] = prompt_id

# def get_prompt_id_for_world(world_id: str) -> str:
#     try:
#         return prompt_world_map[world_id]
#     except:
#         raise KeyError(f'unknown world_id: {world_id}')

# ---------------------- test -----------------------

# des = "A glowing futuristic plaza with holographic stalls and flowing light, silhouettes trading radiant memory orbs, mood vibrant and optimistic, speculative art, cinematic, neon reflections, painterly surreal textures."
# des = "A crumbling memory bazaar beneath a fractured sky, holograms flicker across ruined towers, shadowy figures wander exchanging fading light, mood tense and collapsing, dystopian speculative art, cinematic and surreal."
# des = "A vast urban memory exchange hall under soft blue neon glow, crowds drift calmly, atmosphere balanced between wonder and unease, speculative art style, cinematic lighting, surreal painterly tones."
# des = "A serene riverside city glowing with holographic blossoms, silhouettes exchange gentle streams of light, atmosphere calm and harmonious, speculative art, cinematic, surreal, painterly tones with warm radiant hues."
des = "Envision a randomized perspective within a vibrant, futuristic museum displaying an array of odd, peculiar, and extraordinary art, alongside massive 3D sculptures and enormous paintings. The gallery boasts meticulous architecture characterized by photorealistic and maximalist designs, with each art piece illuminated by spotlights. The ambiance is heightened by surrealistic lighting, augmenting the immersive experience."
cleaned_text = clean_llm_description(des)

payload = build_prompt_payload(cleaned_text)

# print(json.dumps(payload, indent=2, ensure_ascii=False))

prompt_id = enqueue_render(payload)
print("prompt_id is: ", prompt_id)

imagelocation = get_image_location(prompt_id)
print("image path is ", imagelocation.filename, imagelocation.subfolder, imagelocation.type)

content = fetch_png_bytes(imagelocation)
print("png bytes: ", content[:8])