import { useNavigate } from "react-router-dom";
import BasePage from "../components/BasePage/BasePage.jsx";
import Button from "../components/Button/Button.jsx";
import "./HowToScreen.css";
const HowToScreen = () => {
  /* useNavigate hook allows navigation between screens*/
  const navigate = useNavigate();

  /*
    HowToScreen component provides instructions on how to play the game.
  */
  return (
    <BasePage>
      <h1 className="title">Instructions</h1>
      <div className="text-container">
      <p className="text"> Welcome! to The Future Of Memories. In this interactive experience, you will navigate a world shaped by your decisions on neurotechnology and ethics.</p>
        
      <h2 className="subheading">Read the Scenario</h2>
      <p className="text">
        Each level begins with a short narrative scenario generated by advanced AI systems. These reflect real-world neuroscience concepts and speculative futures.
      </p>

      <h2 className="subheading">Make Your Decision</h2>
      <p className="text">
        After the scenario, you’ll be asked a key ethical or scientific question. Your responses influence how neurotechnology advances and is applied in the world.
      </p>

      <h2 className="subheading">See the Impact</h2>
      <p className="text">
        At the end of your journey, an AI-generated artwork visualizes the world you shaped, showing the cumulative effects of your decisions.
      </p>
      <div className="button-group">
        <Button baseButton="btn-back" action={() => navigate("/")} title="Back" />
      </div>
      </div>
    </BasePage>
  );
};
export default HowToScreen;
