import { useNavigate } from "react-router-dom";
import BasePage from "./BasePage.jsx";
import Button from "../components/Button/Button.jsx";

/**
 * HowToScreen component
 *
 * This screen provides players with instructions on how to play the game.
 * It introduces the gameplay loop:
 *  - Reading scenarios
 *  - Making ethical/scientific decisions
 *  - Seeing the cumulative impact of choices
 *
 * Features:
 * - Displays structured instructions with headings and paragraphs.
 * - Uses `BasePage` for consistent layout and styling.
 * - Provides a "Back" button to return to the home screen.
 *
 * @component
 * @returns {JSX.Element} The instructional screen with game rules and navigation.
 */
const HowToScreen = () => {
  // Hook for navigation between routes
  const navigate = useNavigate();

  return (
    <BasePage>
      <div className="menu-glass howto">
        <h1 className="title">Instructions</h1>
        <p className="text">
          Welcome! to <i>The Future Of Memories </i>. In this interactive experience,
          you will navigate a world shaped by your decisions on neurotechnology and ethics.
        </p>

        {/* Step 1: Scenario */}
        <div className="subheading">Read the Scenario</div>
        <p className="text">
          Each level begins with a short narrative scenario generated by advanced AI systems.
          These reflect real-world neuroscience concepts and speculative futures.
        </p>

        {/* Step 2: Decision */}
        <div className="subheading">Make Your Decision</div>
        <p className="text">
          After the scenario, you’ll be asked a key ethical or scientific question.
          Your responses influence how neurotechnology advances and is applied in the world.
        </p>

        {/* Step 3: Impact */}
        <div className="subheading">See the Impact</div>
        <p className="text">
          At the end of your journey, an AI-generated artwork visualizes the world you shaped,
          showing the cumulative effects of your decisions.
        </p>


      </div>
      {/* Navigation Button */}
      <div className="button-group">
        <Button baseButton="btn-exit" action={() => navigate("/")} title="Back" />
      </div>
    </BasePage>
  );
};

export default HowToScreen;
